package core.java.exception;

public enum ErrorCode {
    SOUP_EXCEPTION,
    CONFIGURATION_EXCEPTION,
    DEPENDENCY_EXCEPTION,
    RECEIVER_EXCEPTION,
    WORD_RECEIVER,
    STRICT_RECEIVER,
    DIMENSIONS_RECEIVER,
    ORIENTATION_RECEIVER
}